### ISSUE TITLE
nginx 配置域名 https 登录提示密码错误 

### ISSUE THREAD

**Issue by hale177** [tuituidan/team-nav#10]
在 team-nav 前面加了一个 nginx 并配上了 https ，登录时提示密码错误 

但如果是去掉nginx https ，登录没有问题 

![image](https://user-images.githubusercontent.com/116779418/198214606-5af7a011-8352-41c8-8ccc-66dfb8f2878f.png)
![image](https://user-images.githubusercontent.com/116779418/198215148-8ba71d2a-69d3-4f8a-8744-46323caf0600.png)

**Comment by tuituidan** [comment]
从错误上看，就是`https`请求了`http`被阻断了，`spring security`在启动时就已经定下了协议类型，重定向就走`http`了，https://blog.csdn.net/zhuping2002/article/details/109848759，试试这个是否可以解决呢

**Comment by tuituidan** [comment]
![截图_选择区域_20221030113539](https://user-images.githubusercontent.com/20398244/198861420-7a0ace65-f0c0-4ca8-a0be-297c6d3ef677.png)
你好，我这边尝试了一下未能复现该问题，nginx下载的最新版本，SSL证书从阿里云申请的，手动部署和docker部署，再用nginx反向代理过去，都正常登录了，你那边有详细的部署步骤和复现步骤吗
