### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wangbf19740612** [tuituidan/team-nav#11]
1、建议设置侧边栏默认收起和展开的参数
2、建议搜索时不区分大小写
3、IE11下搜索汉字内容404，希望能修复下

完美的导航，感谢！！

**Comment by tuituidan** [comment]
非常感谢您的建议，已在最新v1.0.4中修改
 - 左侧菜单收起和展开记录到了`localStorage`中，这样记录的就是个人习惯，不影响其他人
 - 搜索已经不区分大小写，且不再实时搜索，需要按回车或者点击搜索框中的icon
 - IE下中文搜索报错已解决，确实没怎么在IE下测试过，目前也只有首页做了IE兼容

**Comment by wangbf19740612** [comment]
非常感谢，测试基本没有问题
第一项可能是我表述不太清楚，建议事和登陆一样设置一个参数，可以根据参数设置左侧菜单默认状态为收起或展开，这里仅泛指首页面：）

**Comment by hale177** [comment]
侧边栏收起和展开没必要搞个默认参数，只需要能保持上一次动作即可 
比如第1次点了收起状态，然后点页面其他任何操作，侧边栏还是一直保持收起
（而 v1.0.3版操作逻辑是收起后，点页面其他操作，侧边栏又展开了）


另个人倒是觉得实时搜索功能挺好用，效率党福音啊  ：） @tuituidan

**Comment by wangbf19740612** [comment]
> 侧边栏收起和展开没必要搞个默认参数，只需要能保持上一次动作即可 比如第1次点了收起状态，然后点页面其他任何操作，侧边栏还是一直保持收起 （而 v1.0.3版操作逻辑是收起后，点页面其他操作，侧边栏又展开了）
> 
> 另个人倒是觉得实时搜索功能挺好用，效率党福音啊 ：） @tuituidan

场景不同，所以需求不同的

**Comment by tuituidan** [comment]
@wangbf19740612 关于侧边栏我之前是理解了你的意思，只是没能想象到你的场景，我和 @hale177  的观点一致，要不要收起这个属于个人习惯，一般用分辨率较低的笔记本可能大多时候需要收起，我自己基本都没收起过，所以我改成了在localStorage中记住上一次的操作，这样的话经常需要收起的人最多也就是第一次自己点一下收起，不会影响到其他人。我这边暂时没能理解必须要加这样一个默认配置的场景，你能否描述一下你实际的场景，咱们再看是否实现它

**Comment by tuituidan** [comment]
@hale177  可能是我本地测试数据较大，在多个人同时进行搜索时感觉略有卡顿，毕竟每输入一个字符就有一个查询sql执行，而多数时候的输入比如只有一两个字符时都是属于多余无效的查询，不实时最多也就是多按一下回车键，确定好自己要搜索的关键字再搜索。
不过首页是没分页的，所有数据都已经到了前端，需要实时的话，搜索用js在前端实现应该就还好

**Comment by wangbf19740612** [comment]
@tuituidan 实际的场景应用就是只有一个分类，所以.....

**Comment by hale177** [comment]
> @hale177 可能是我本地测试数据较大，在多个人同时进行搜索时感觉略有卡顿，毕竟每输入一个字符就有一个查询sql执行，而多数时候的输入比如只有一两个字符时都是属于多余无效的查询，不实时最多也就是多按一下回车键，确定好自己要搜索的关键字再搜索。 不过首页是没分页的，所有数据都已经到了前端，需要实时的话，搜索用js在前端实现应该就还好

懂了 ，我这边分类也很多，大数据量手动点击搜索确实会好很多
