### ISSUE TITLE
关于link私密分类

### ISSUE THREAD

**Issue by hale177** [tuituidan/team-nav#12]
请教下，这是一个什么使用场景 

![image](https://user-images.githubusercontent.com/116779418/199642634-22200755-71c2-4ac5-a202-6b0a205335f7.png)

**Comment by tuituidan** [comment]
一般只有团队内部人员才有账号密码登录，设为私密卡片，只有登录了才会在首页显示，可以放一些服务器数据库密码什么的，只分享给团队内部人员，首页是不登录就可以访问的，其他团队的人进来只看非私密的卡片

**Comment by hale177** [comment]
> 一般只有团队内部人员才有账号密码登录，设为私密卡片，只有登录了才会在首页显示，可以放一些服务器数据库密码什么的，只分享给团队内部人员，首页是不登录就可以访问的，其他团队的人进来只看非私密的卡片

验了下，符合预期  nice ！
