### ISSUE TITLE
docker的版本怎么改密码呢

### ISSUE THREAD

**Issue by OxYancy** [tuituidan/team-nav#14]
docker的版本怎么改密码呢

**Comment by tuituidan** [comment]
@986244073 登录的账号密码是配置在`application.yml`里面的，`docker`的`-e`参数就可以替换application.yml里面的配置，也可以把`config/application.yml`文件通过`-v`参数映射出来，可以随时修改里面的任一配置

**Comment by Songxwn** [comment]
希望能在前端更改密码，这样更方便一些。

**Comment by tuituidan** [comment]
@Songxwn  已在develop分支支持了密码修改，暂不发版，可以先自行打包吧
![admin-system](https://user-images.githubusercontent.com/20398244/202465155-6c1ea9cf-2cb8-4a31-91c0-f12b0854a192.png)

**Comment by Songxwn** [comment]
感谢作者支持😀
