### ISSUE TITLE
新版本普通卡片添加后前台点击无法新窗口打开...

### ISSUE THREAD

**Issue by wangbf19740612** [tuituidan/team-nav#17]
windows环境，批处理方式运行jar包
测试多台机器均存在此问题，F12查看有如下错误
![image](https://user-images.githubusercontent.com/44603119/204453907-43ee10f3-bdc1-401c-9d97-75ac8bd8fd90.png)
希望大佬能检查处理下，非常感谢

**Comment by tuituidan** [comment]
@wangbf19740612 
这就尴尬了，没测到就匆匆发布了，非常抱歉，已修复，并重新发布了1.0.8

**Comment by wangbf19740612** [comment]
实测已修复，谢谢大佬
