### ISSUE TITLE
支持 logo 更换

### ISSUE THREAD

**Issue by hale177** [tuituidan/team-nav#18]

**Comment by tuituidan** [comment]
@hale177  logo在最新1.1.0版本已支持在设置中进行修改，favicon使用的也是logo的图片，会同步修改
文字的修改就是设置里面的【服务名称】，可能名字没取好，不好理解，我改成了网站标题
![image](https://user-images.githubusercontent.com/20398244/236678229-1cb45f0c-7b84-41be-aed2-66feb614bf57.png)

**Comment by hale177** [comment]
nice ~ good job
