### ISSUE TITLE
docker部署映射config

### ISSUE THREAD

**Issue by rrrzr** [tuituidan/team-nav#19]
你好，在使用dokcer部署时，通过-v 映射/config 文件夹，但是容器起来后，宿主机对应的文件夹是空内容；是什么原因呀

**Comment by Songxwn** [comment]
docker 镜像默认是没有配置文件的，手动创建即可。 https://songxwn.com/team_nav

**Comment by tuituidan** [comment]
@ucnu 没有设置默认config文件夹，正如 @Songxwn  说的，手动创建该文件夹并在其中添加`application.yml`即可覆盖配置，或者直接用`-e`参数替换`application.yml`中的配置

**Comment by rrrzr** [comment]
已解决，谢谢。
