### ISSUE TITLE
左侧导航太宽了

### ISSUE THREAD

**Issue by zhangshuanlai** [tuituidan/team-nav#22]
个人觉得左边的导航太宽了，有点丑

**Comment by zhangshuanlai** [comment]
如果能后台设置宽度就好了

**Comment by tuituidan** [comment]
@zhangshuanlai   之前使用的时候，右侧菜单由于放的就是研发项目名称，有些项目名称非常长，显示前面几个字有时都看不出来是什么，所以做的比较宽，右侧现在新增了【布局大小】设置，可调整整体布局大小，默认为较大，设置为中等即可整体调小，包括右侧菜单宽度
![image](https://user-images.githubusercontent.com/20398244/236678469-fbb8e949-3673-4a6b-b712-12b46af8e356.png)
