### ISSUE TITLE
页面样式有错误，需要修正

### ISSUE THREAD

**Issue by wangbf19740612** [tuituidan/team-nav#24]
谷歌浏览器下：
建立了四个测试分类，如下图：
![1](https://user-images.githubusercontent.com/44603119/237007597-77512304-7002-4f75-982b-8b9ae4875b1a.PNG)
收起侧边栏后显示的类别会减少
![2](https://user-images.githubusercontent.com/44603119/237007705-c6537d26-2ed2-476d-8acf-c36464ae1282.PNG)

IE11下面：
收起侧栏分类显示是正常的，但打开后，页面混乱了
![5](https://user-images.githubusercontent.com/44603119/237007835-5c4cae8d-05ba-4d1c-8998-2b85a2f8cda7.PNG)
收起侧栏时，网站图标高度顶到了
![4](https://user-images.githubusercontent.com/44603119/237007946-3e68304b-06f1-4c11-9975-a32d0298b4d5.PNG)

另：替换jar包内的favicon.ico不生效，感觉是调用了logo.png文件吧

希望大佬得空修复一下，谢谢

**Comment by tuituidan** [comment]
@wangbf19740612 感谢指正，最新的`v1.1.1`版本左侧菜单显示问题已经修复，IE下的问题是因为写了css变量，而IE不支持css变量导致的，没想到你们还在用IE，现在已经显示正常了。因为logo支持了修改，为了统一，就弃用了默认路径下的`favicon.ico`，你们也不是必须要logo图片和favicon不一致吧？

**Comment by wangbf19740612** [comment]
@tuituidan 是的，确实是需要logo和favicon不一致，这块建议还是分开比较好哈
