### ISSUE TITLE
feature: 首页公告功能

### ISSUE THREAD

**Issue by hale177** [tuituidan/team-nav#26]
如图，在首页搜索框右侧空白区域 ，增加公告通知功能，比如 team 内部一些 xxx 重要系统xxx时间上线/下线 等类似通知

1，通知条数不多时，静态显示 ，多条时可滚动显示，比如 滚动 显示 5秒再滚下一条（有点像平时去银行大厅排队电子屏消息）
2，后台可以提供一个 html 编写框，用户自由控制颜色，字体大小等

<img width="760" alt="1683687984(1)" src="https://github.com/tuituidan/team-nav/assets/116779418/3ea7ea3f-fc8a-4637-8e8d-5e01682e3b6c">

**Comment by tuituidan** [comment]
@hale177 有个项目发布倒计时功能，在系统设置里面开启，你看看是否是你要的
![image](https://github.com/tuituidan/team-nav/assets/20398244/0e9b5afc-3e91-4484-b946-3f91d9ec2386)

**Comment by tuituidan** [comment]
功能名称虽然叫发布倒计时，但是这个通知内容是自定义的，不管是系统上线还是下线，就看怎么填描述，只是比起普通文本通知，始终多个倒计时提醒
