### ISSUE TITLE
后台logo上传问题和一点建议

### ISSUE THREAD

**Issue by wangbf19740612** [tuituidan/team-nav#27]
最新版本后台上传logo后，一天之后上传的目录自动删除，logo图片失效，需再次上传，然后再隔一天同样会出现上述情况，不知道是我配置问题还是代码问题，大佬给排查下吧，谢谢
另：建议还是将logo及favicon分开处理比较好

有时间可以考虑以下建议
1、分类支持二级分类
2、增加主题功能（更换侧边栏配色或自定义配色等）

**Comment by tuituidan** [comment]
@wangbf19740612 是个bug，可以先将`clear-useless-files.enable=false`加入到配置中，这样就不会被清理掉了，下次发版再解决这个bug
