### ISSUE TITLE
网站LOGO 第二天总是无法加载

### ISSUE THREAD

**Issue by zhouweisong** [tuituidan/team-nav#28]
<img width="474" alt="image" src="https://github.com/tuituidan/team-nav/assets/13566805/200ef865-9908-4bd7-bc7e-6dc3159a0a08">

为什么我的这个图片 第二天准变成这样，每天都得上传一次

**Comment by tuituidan** [comment]
@zhouweisong 这是上版本的一个bug，目前已经在develop分支解决，只是还没发版，可以先将clear-useless-files.enable=false加入到配置中，这样就不会被清理掉了；或者你基于develop分支重新打个包替换

**Comment by tuituidan** [comment]
@zhouweisong 已在最新V1.1.2版本中更新
