### ISSUE TITLE
大神能写一下team-nav docker容器的版本升级流程么？我想从 1.1.1 升级到1.1.2

### ISSUE THREAD

**Issue by zhouweisong** [tuituidan/team-nav#29]
搭建容器简单，但是我已经把公司的所有导航链接都维护好了，怕升级版本的时候 把数据丢了

**Comment by zhouweisong** [comment]
希望加一个 数据备份 和  数据恢复的功能，这样服务迁移啥的比较方便

**Comment by tuituidan** [comment]
@zhouweisong 按照readme里面的docker命令启动，上传文件资源(`ext-resources`)和数据库文件(`database`)的存储都是挂载出来了的，同样的命令只改版本号再启动即可，数据不会有任何丢失，如果你一开始的启动命令没有把`database`和`ext-resources`两个文件夹挂载出来，就通过docker命令从容器中拷贝出来放到宿主机上，然后按readme里面那样挂载，资源和数据也能映射到新环境。
