### ISSUE TITLE
能不能支持多级分类

### ISSUE THREAD

**Issue by siyiys** [tuituidan/team-nav#32]
你好，能不能支持多级分类。比如我有10个项目，每个项目5个地址，每个项目分开发、测试等环境。如果是一级分类，这样左边栏非常多的目录，如果支持多级分类就比较好整理了，地址可以添加到二级里面。
类似：
<img width="1336" alt="image" src="https://github.com/tuituidan/team-nav/assets/7286074/ee2a3aa3-8041-4fe4-a624-9b44d8ae3f9e">

**Comment by tuituidan** [comment]
@siyiys 之前没有做成多级分类，是因为使用过程中经常需要新增和移除，拖拽排序功能就显得比较重要，而多级分类在后台维护页面是个树结构，不同层级之间是不能一起拖拽排序的。不过现在发现只有一级分类确实有些不方便，所以下一个版本考虑做成两级分类，即一个页面上面放两个表格，分别放两级分类，这样可以保留拖拽排序。你截图的属于三级分类了，在希望保留拖拽排序的情况下，暂时没有想到更好的交互方式。

**Comment by hale177** [comment]
支持，这个feature 很不错~

**Comment by tuituidan** [comment]
@siyiys @hale177 已在最新2.0.0版本中实现

**Comment by siyiys** [comment]
非常感谢！
