### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by EchoGroot** [tuituidan/team-nav#4]
朱哥，我之前在huayu，找你要导航给np用，现在离开了huayu，觉得以前那个团队导航很好用，也想搞一个。各种搜，终于找到了，哈哈哈。
提点小建议哈
1. 这个项目的readme描述太少了，没有demo，也没有图片，导致这么好的项目没埋没了。你看同类的都有清晰描述：https://github.com/lework/lenav，我没找到你这个项目之前，打算自己写个后端服务结合那个lenav用，不过都不是很满意，想着和之前用的差距太大！
2. 公司那边更新，别忘了更github哈，不过认证可以不要，就像现在一样，反正团队内部使用，也没人会去删除啥的
> 希望这个好项目被更多人发现、使用。

**Comment by tuituidan** [comment]
感谢你的使用
确实是之前在公司其实改了很多bug了，一直都没更新到GitHub上来，非常抱歉
移除了公司版本的人员权限管理及sso登录，现在改成了后台管理只有一个管理员可以登录，也就是SpringSecurity实现的那种，直接在application.yml中配置用户名密码，这样账号密码就在自己团队分享就行了

**Comment by EchoGroot** [comment]
这样挺好的👍👍👍
1、管理权限确实应该收敛到团队内部，
2、提供一个默认账号就行，没必要搞账号注册，权限管理那套。

**Comment by hale177** [comment]
是否考虑增加一个 ldap 登录呢（只做登录，不考虑RBAC 权限分配）
因为现在很多公司都有统一ldap认证系统， 增删 link 时可以给在ldap里集中授权谁可以登录team-nav 进行维护管理

ldap 对接相关配置可以放到 application.yml 里

**Comment by tuituidan** [comment]
非常感谢您的建议
但其他登录方式暂时不会考虑集成了，很多公司都有自己的一套统一认证方式，确实众口难调，集成多了反而影响其他人的部署，本项目定位主要是小而精，暂时只会在团队网址导航这个核心功能上打磨。
您可以单独起一个分支集成推上来分享给其他人，但不会合到主分支
