### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wangbf19740612** [tuituidan/team-nav#40]
1、导航页面分类图标过小，能否加大图标的显示尺寸
2、类1.14版本，将布局设置的按钮独立出来，可减少点击次数，布局大小调节功能能否恢复，未登录状态图标希望能够恢复为1.14版本图标，能更好的保持一致性
3、测试附件上传最多只能10个，能否去除限制，描述也是如此限制为200字符，某些情况下不够...接上次建议，最好在当前页面弹出卡片框而不是使用tooltip
4、静态网站tooltip会暴露路径，建议隐藏处理一下

烦请大佬考虑一下是否可行，谢谢

**Comment by tuituidan** [comment]
感谢你的提的意见，让这个项目越来越好用：
1、卡片大小这个下个版本加吧。
2、布局设置页并不常用和登录其实都不常用，自己的电脑通常登录一次就记住并自动登录，平时基本就不会再去点，就没必要纠结是放出来还是收起来了吧
3、附件功能只是想临时放一些少量的文件，文字描述也是一样，只是一些少量描述，这个导航服务并不想做成一个文件管理服务，后续有必要可能也会单独做一个文件服务，支持各种文件的在线预览，更多的信息描述就放文件服务里面，通过链接跳过去，现成的文件服务现有的也有很多，比如zfile这种，如果你有放更多文件的需求，可以考虑单独搭建这样的一个服务。
4、静态网站是支持单独配置nginx来访问的，通过nginx的配置就能达到隐藏全路径的效果
