### ISSUE TITLE
2.0.1 bug: chrome 浏览器，点击后台管理无法跳转到管理页面

### ISSUE THREAD

**Issue by oneisall8955** [tuituidan/team-nav#41]
如图，从2.0.0升级到2.0.1后，Chrome浏览器从前台点击后台管理按钮，浏览器重定向到路由`/#/admin/category`
点击按钮后会自动跳转到前台。chrome浏览器把缓存清空了仍然出现

![image](https://github.com/tuituidan/team-nav/assets/44989283/e42409a9-8674-42f4-9e36-6ea54540d1d8)

![image](https://github.com/tuituidan/team-nav/assets/44989283/085c0c22-d121-4c98-8e0f-f5e0c2c8e7f0)

**Comment by tuituidan** [comment]
@oneisall8955 你是想进后台，但是始终跳转回前台吗，后台因为没有做权限控制，所以目前是只有管理员角色才能进后台管理，你给要进后台的账号分配一下管理员角色

**Comment by oneisall8955** [comment]
@tuituidan 好的，我试一下，如果是这个原因，报错或提示会更好些

-----------
登录admin账号可以正常跳转到前台，但是我用普通用户，赋予管理员角色，仍然不行

![image](https://github.com/tuituidan/team-nav/assets/44989283/09b98aaf-35b6-492b-bae6-fbe4543ed2a0)

**Comment by tuituidan** [comment]
@oneisall8955 是2.0.1的时候改出的bug，目前已经修复推到develop分支了，你可以自行用最新代码打包替换一下，下个版本再发

**Comment by oneisall8955** [comment]
@tuituidan 好的，谢谢~

**Comment by tuituidan** [comment]
@oneisall8955 管理员角色无法进入后台的bug，已经在最新2.0.2中发布了
