### ISSUE TITLE
添加内网link 链接bug 

### ISSUE THREAD

**Issue by hale177** [tuituidan/team-nav#9]
部署起来了，挺好用的，满足需求 ，但有个小bug：
 
如果我要添加一个内网 link 链接（team-nav和这个 link 之间网络不通），team-nav自动获取图标icon 的功能会一直卡住获取不到且不会超时

建议application.yml 添加一个  timeout 选项或默认3秒不通直接就提示个错误即可，然后自己上传一个图标icon

**Comment by tuituidan** [comment]
朱军函：已收到

**Comment by hale177** [comment]
> 
![image](https://user-images.githubusercontent.com/116779418/198186158-f31f263c-d15d-452a-be29-8bef3fc8f4f9.png)

**Comment by tuituidan** [comment]
感谢提醒，已在develop分支修复，我尝试了一下，完全不通的链接，还是会直接结束请求，但连接上了却一直不返回就会出现你说的这种情况，现在已经去掉了请求遮罩，超时时间设为5s，因为是两种方式获取favicon.ico，最多等待10秒，但因为没有遮罩，表单可随时提交，不必等待获取favicon.ico的请求完成
![截图_选择区域_20221029110441](https://user-images.githubusercontent.com/20398244/198794369-aa85c69a-72ae-4029-953a-58afc13dd6a1.png)

**Comment by hale177** [comment]
好滴~~  等你发 release 或 docker image 我再更新试试测一把
